### ISSUE TITLE
grid flex layout attributes

### ISSUE THREAD

**Issue by frankkoenigstein** [ionic-team/ionic#10753]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Currently it is not possible to assign attributes like `justify-content-start` to a grid.
This is only possible for rows.

**Expected behavior:**

In combination with an height attribute like
```css
 [height-100] {
     height: 100%;
 }
```

a grid can be used to adjust its content more flexible:
```html

<ion-grid justify-content-center height-100>
<!-- ... -->
</ion-grid>

```

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

I suggest to extent the grid mixin in `grid.mixins.scss` the following way:
```scss
@mixin make-grid($padding-width: $grid-padding-width) {
  padding: $padding-width / 2;
  margin-left: auto;
  margin-right: auto;
  width: 100%;

  // Remove the padding from the grid and all immediate children columns
  &[no-padding] {
    padding: 0;

    > .row > .col {
      padding: 0;
    }
  }

  &[nowrap] {
    flex-wrap: nowrap;
  }

  &[wrap-reverse] {
    flex-wrap: wrap-reverse;
  }

  &[align-items-start] {
    align-items: flex-start;
  }

  &[align-items-center] {
    align-items: center;
  }

  &[align-items-end] {
    align-items: flex-end;
  }

  &[align-items-stretch] {
    align-items: stretch;
  }

  &[align-items-baseline] {
    align-items: baseline;
  }

  &[justify-content-start] {
    justify-content: flex-start;
  }

  &[justify-content-center] {
    justify-content: center;
  }

  &[justify-content-end] {
    justify-content: flex-end;
  }

  &[justify-content-around] {
    justify-content: space-around;
  }

  &[justify-content-between] {
    justify-content: space-between;
  }
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

```
