### ISSUE TITLE
Can't print the entire page when I have a scrollable content with many items

### ISSUE THREAD

**Issue by adsonrocha** [ionic-team/ionic#12002]
**Ionic version:** 
[ x ] **3.x**

**I'm submitting a ...**
[ x ] bug report

**Current behavior:**
Can't print the entire page when I have a scrollable content with many items. I am using the native browser print function: window.print()

**Expected behavior:**
Print a document with many pages using the native browser print function: window.print()

**Steps to reproduce:**
ionic start myProject sidemenu
cd myProject
ionic g page listPage

**at listPage.html:**
**Related code:**
```
<ion-list>
<ion-item *ngFor="let item of items">{{item}}</ion-item>
</ion-list>
<button ion-button (click)="print()">Print</button>
```
**at listPage.ts:**
``` typescript
print(){
window.print();
}
```

**Other information:**
```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Does this issue also happen in a vanilla Angular app that uses an *ngFor list?

**Comment by adsonrocha** [comment]
Yes @jgw96 , it does. 
I managed the problem with this code at app.css:

``` css
@media print{
  ion-header{ display: none !important; }  

  body, .app-root, .split-pane, .ion-page, ion-app, ion-nav { contain: none; }
  body, ion-nav{ overflow: initial; }
  body{ position: static; }

  [ion-content-print]{ overflow-y: visible !important; position: relative; }
}
```
**and this template at my component:

``` html
<ion-header> ... </ion-header>
<section ion-content-print>
my printable content here
</section>
```
As you can see, i had to remove printable contents from ``<ion-content>``.

I think the problem is related to that ``contain``  and ``overflow`` css properties.
