### ISSUE TITLE
Prod built main.css does not include constant+env declarations used for iPhone X

### ISSUE THREAD

**Issue by ajcrites** [ionic-team/ionic#13437]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
After `ionic cordova build ios --prod`, the built `main.css` does not include the `constant()` properties for some iOS 11+ properties which leads to some issues including footer tabs not having the necessary padding on iPhone X.

**Expected behavior:**
The output should include both the `constant` and `env` declarations.

**Steps to reproduce:**
Build a project for iOS using `ionic cordova build ios --prod`. If running on an iPhone X device or simulator, you can see that footers including tabs do not have the necessary bottom padding for iOS at least up to 11.1

If you do not use `--prod`, the output CSS is correct.

**Related code:**
main.css without `--prod` looks like:

```css
.ios .tabs .tabbar {
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}
```

With `--prod`, the duplicate declaration appears to be stripped out so you get

```css
.ios .tabs .tabbar{padding-bottom:env(safe-area-inset-bottom)}
```
only

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/acrites/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v8.7.0
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55
```
