### ISSUE TITLE
v4: Allow customizing SCSS variables used in Ionic (or add more css variables)

### ISSUE THREAD

**Issue by fifafu** [ionic-team/ionic#14624]
# Feature Request
If I haven't missed anything, Ionic v4 alpha only allows to override the css variables and not the scss variables used in the Ionic framework. This limits the customizability a lot.

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/Users/andi/.nvm/versions/node/v8.11.1/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.7
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Feature Request**
Currently it doesn't seem to be possible to change the SCSS variables used in Ionic 4. This is really bad for some of the enterprise apps I'm working on, because they require a custom corporate font and various other changes. The changes I need to make are not covered by the currently available css variables but would be easy to do with the Ionic SCSS variables.

In Ionic 1/2/3 this was easy to do by setting custom values to the variables in variables.scss. In Ionic 4 alpha this doesn't seem to be possible without creating a custom build of the Ionic Framework.

I'm currently using some ugly css overrides to workaround this but I'd very much like to not do this.

**Describe Preferred Solution**
Allow customizing all the scss variables

**Describe Alternatives**
Make everything available as css variables

**Comment by kael** [comment]
[This](https://github.com/ionic-team/ionic-docs/blob/04c08b4debd23eb8323c908ba49c6f43a2e36e72/src/content/theming/advanced.md#layered-colors) might help.

**Comment by kael** [comment]
As far as I understand, default SCSS colors values can be overridden.

Create a custom color using the [color generator](https://github.com/ionic-team/ionic-docs/blob/master/src/content/theming/color-generator.md), define the custom color values in the `src/global/app.css` (don't recall which file for Ionic-Angular) :
```scss
/** Ionic CSS Variables **/
:root {

  /** primary **/
  --ion-color-secondary: #3880ff;
  --ion-color-secondary-rgb: 56,128,255;
  --ion-color-secondary-contrast: #ffffff;
  --ion-color-secondary-contrast-rgb: 255,255,255;
  --ion-color-secondary-shade: #3171e0;
  --ion-color-secondary-tint: #4c8dff;
}
``` 

Define the `globalStyle` file path in `stencil.config.js`:
```js
exports.config = {
  ...
  globalStyle: 'src/global/app.css',
}
```

And that should be it, using `color='primary'` as usual.
