### ISSUE TITLE
[Ionic v4.0.0-beta.8] popover lost arrows

### ISSUE THREAD

**Issue by bleuscyther** [ionic-team/ionic#15509]
The arrow is no longer displaying even in IOS.
As a temporary fix i have to set 

``` scss
.popover-arrow{
    display: block !important;
}
```
