### ISSUE TITLE
[ionic 4-beta] Popover conflicts with bootstrap 4

### ISSUE THREAD

**Issue by beginor** [ionic-team/ionic#15589]
## [ionic 4-beta] Popover conflicts with bootstrap 4

When using ionic and bootstrap, the Popover component's style is confict with Bootstrap's Popover.

They all use `.popover` class, but bootstrap has defined `max-width` `border` `background-color`, this cause ionic popover component miss behavior.

<img width="595" alt="screen shot 2018-09-14 at 06 52 47" src="https://user-images.githubusercontent.com/159065/45520261-1e660480-b7eb-11e8-9c01-ef30c9508da3.png">

<img width="595" alt="screen shot 2018-09-14 at 06 52 53" src="https://user-images.githubusercontent.com/159065/45520275-2d4cb700-b7eb-11e8-9845-d010fa304cc8.png">

current fix is add custom class to override bootstrap's popover:

```css
.ion-popover {
  max-width: 100% !important;
  border-radius: 0 !important;
  border: none !important;
  background-color: transparent !important;
}
```

```ts
public async showPopover($event: Event): Promise<void> {
    const popover = await this.popoverCtl.create({
        component: PopoverComponent,
        componentProps: {},
        event: $event,
        showBackdrop: true,
        cssClass: 'ion-popover'
    });
    await popover.present();
    const result = await popover.onDidDismiss();
    console.log(result);
}
```
