### ISSUE TITLE
[Ionic V4-beta.12] Theme variables only applied on iOS

### ISSUE THREAD

**Issue by selipso** [ionic-team/ionic#15790]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v10.11.0
   npm    : 6.4.1
   OS     : Linux 4.15

```

**Describe the Bug**
Primary theme color only applied to the bottom of iOS navbars. On the web and android, the navbar icons are still blue. Screenshots included:

**_Theme not applied - Chrome (Ubuntu), Android (via Ionic DevApp)_**
 
![screenshot from 2018-09-28 01 55 24](https://user-images.githubusercontent.com/5407481/46198656-d7374380-c2c1-11e8-80d2-a0ddacedf295.png)

**_Theme applied on iOS (via Ionic DevApp)_**

![img_2922](https://user-images.githubusercontent.com/5407481/46198855-4c0a7d80-c2c2-11e8-9b79-3ced542611a7.PNG)

**Steps to Reproduce**
1. Create new ionic v4 app using tabs template.
2. Install the beta.12 release
3. Fire up the app with `ionic serve -c`
4. Check out the tabs example

**Related Code**
Add the following styles to your src/app/theme/variables.scss file, overwriting existing default styles:

```scss
:root {
  --ion-color-primary: #FF530C;
  --ion-color-primary-rgb: 255,83,12;
  --ion-color-primary-contrast: #ffffff;
  --ion-color-primary-contrast-rgb: 255,255,255;
  --ion-color-primary-shade: #e0490b;
  --ion-color-primary-tint: #ff6424;
}
```

**Expected Behavior**
Ionic tabs on all browsers should be able to handle the orange theme and change their background color accordingly.
