### ISSUE TITLE
ion-toggle doesn't work on click event (Ionic 4)

### ISSUE THREAD

**Issue by ThomasLohmann** [ionic-team/ionic#15898]
Hi there,

ion-toggle doesn't work on click event e.g. <ion-toggle (click)=samleFunction()> </ion-toggle>

In Ionic 3 it works. 

Please fix this bug.

Kind regards,
Thomas

**Comment by fmendoza** [comment]
I had the same issue and I fixed it adding the following css rule
```css
ion-toggle {
    pointer-events: all;
}
```
