### ISSUE TITLE
Hide tab bar and footer when keyboard is open

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic#16419]
<img width="458" alt="screen shot 2018-11-20 at 8 01 51 pm" src="https://user-images.githubusercontent.com/452425/48863389-cc170600-ed8e-11e8-83af-1db910ee4dde.png">

**Comment by mlynch** [comment]
From @jcesarmobile: "I think keyboard already handles that, but you have to configure it to not resize
I think it's the `<preference name="KeyboardResizeMode" value="ionic" />` or `<preference name="KeyboardResize" value="false" />`"

So this could be a case of the wrong defaults in our starters

**Comment by jcesarmobile** [comment]
The resize modes and keyboard resize are only implemented for iOS at the moment. Not really sure if it's possible on Android

**Comment by viniciosyals** [comment]
You can do this:

[Install keyboard native plugin](https://beta.ionicframework.com/docs/native/keyboard)
```
ionic cordova plugin add cordova-plugin-ionic-keyboard
npm install --save @ionic-native/keyboard@beta
```

tabs.page.html
```html
...
<ion-tab-bar #tab slot="bottom">
...
```
tabs.page.scss
```css
ion-tab-bar {
	-webkit-transition: transform 0.3s linear, height 0.3s linear; 
	-o-transition: transform 0.3s linear, height 0.3s linear; 
	transition: transform 0.3s linear, height 0.3s linear;
	&.hide {
		transform: translateY(56px);
		height: 0px;
	}
}
```
tabs.module.ts
```javascript
...
import { Keyboard } from '@ionic-native/keyboard/ngx';
...
providers: [
	Keyboard
]
...
```
tabs.page.ts
```javascript
import { Component, OnInit, AfterViewInit, ElementRef, Renderer2, ViewChild } from '@angular/core';
import { Keyboard } from '@ionic-native/keyboard/ngx';

@Component({
	selector: 'app-tabs',
	templateUrl: 'tabs.page.html',
	styleUrls: ['tabs.page.scss']
})
export class TabsPage implements OnInit, AfterViewInit {

	@ViewChild('tab', {read: ElementRef}) tab: ElementRef;
	tabEl : ElementRef;
	
	constructor(
		private renderer: Renderer2,
		private keyboard: Keyboard
	) { }

	ngOnInit() {
		this.keyboard.onKeyboardWillShow().subscribe(() => {
			this.renderer.addClass(this.tab.nativeElement, 'hide');
		});
		this.keyboard.onKeyboardWillHide().subscribe(() => {
			this.renderer.removeClass(this.tab.nativeElement, 'hide');
		});
	}

	ngAfterViewInit() {
		this.tabEl = this.tab.nativeElement;
	}

}
```
