### ISSUE TITLE
[ionic v4] components reinitialize values of CSS vars

### ISSUE THREAD

**Issue by Takkuz** [ionic-team/ionic#16445]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.4.0
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.13.0 (/opt/nvm/versions/node/v10.13.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.18
```

**Describe the Bug**
Modifying a CSS variable in a parent element will not replicate the value inside ion-component when values are reinitialized inside `:host` tag. I noticed trying to change `--highlight-color-focused` of an `ion-item`.

**Steps to Reproduce**
1. Create a new app
2. Add a simple `ion-input` item:  
```html
<ion-list>
  <ion-item>
    <ion-label>Input</ion-label>
    <ion-input></ion-input>
  </ion-item>
</ion-list>
```
3. Change `--highlight-color-focused` value of `ion-content`  
```css
ion-content {
  --highlight-color-focused: var(--ion-color-dark);
}
```
4. The `ion-item` keeps it's default value of `--ion-color-primary`
5. Referencing directly `ion-item` works correctly  
```css
ion-content ion-item {
  --highlight-color-focused: var(--ion-color-dark);
}
```

**Expected Behavior**
I know I can add custom stile to every `ion-item` but I have many layer of custom elements to go through so I would expect that when I change the value of a valid prop of an element it will applied to every child.
