### ISSUE TITLE
Ionic 4.0.0-rc.0 segment indicator not showing up

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#16820]
# Bug Report

**Ionic version:**
`4.0.0-rc.0`

**Current behavior:**
Segment indicator is not showing up when theming with the global CSS variables

**Related code:**

```html
<ion-toolbar class="themed">
  <ion-segment value="delete">
    <ion-segment-button value="create">
      <ion-label>Create</ion-label>
      <ion-icon name="create"></ion-icon>
    </ion-segment-button>
    <ion-segment-button value="delete">
      <ion-label>Delete</ion-label>
      <ion-icon name="trash"></ion-icon>
    </ion-segment-button>
    <ion-segment-button value="upload">
      <ion-label>Upload</ion-label>
      <ion-icon name="cloud-upload"></ion-icon>
    </ion-segment-button>
  </ion-segment>
</ion-toolbar>
```

```css
.themed {
  --ion-toolbar-background: #3880ff;
  --ion-toolbar-color: #fff;
  --ion-toolbar-color-activated: #fff;
  --ion-toolbar-color-unchecked: rgba(255, 255, 255, .6);
  --ion-toolbar-color-checked: #fff;
}
```

**This applies to the conference app**
