### ISSUE TITLE
ion-split-pane: expose max-width as CSS custom property

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#17088]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I want to be able to adjust the max width of the `ion-split-pane` side menu.

**Describe Preferred Solution**

Have a `--max-width` CSS custom property on `ion-split-pane`. Might be as simple as changing

```scss
{ max-width: $split-pane-md-side-max-width; }
```

to

```scss
{ max-width: var(--max-width, $split-pane-md-side-max-width); }
```

**Describe Alternatives**

Only way to currently make it work is to set 

```scss
.menu-pane-visible {
  max-width: 270px !important;
}
```

which applies only for the expanded version. If `max-width` is set on the `ion-menu`, it messes up the backdrop for the collapsed version.

**Comment by brandyscarney** [comment]
I agree with this. We will need to scope/shadow the split-pane component though. It seems as if the current CSS won't even work for IE since it has a CSS variable for border. It will need to be something like the following (not tested):

**split-pane.md.scss**

```css
:host {
  --min-width: #{$split-pane-md-side-min-width};
  --max-width: #{$split-pane-md-side-max-width};
}

:host(.split-pane-visible) .split-pane-side {
  --border: #{$split-pane-md-side-start-border};
}

:host(.split-pane-visible) .split-pane-side[side=end] {
  --border: #{$split-pane-md-side-end-border};
}
```

**split-pane.scss**

```css
:host(.split-pane-visible) .split-pane-side {
  min-width: var(--min-width);
  max-width: var(--max-width);

  border: var(--border);
}
```

Might need to change up the border implementation, but just an idea. cc @manucorporat

**Comment by troyanskiy** [comment]
Hi @brandyscarney
I'm going to create a PR for that issue if you don't mind.

I have small question.

Is there any reason to have not really optimized code (duplicated lines) in the scss?
For example `split-pane.ios.scss` file:
Original:
```scss
@import "./split-pane";
@import "./split-pane.ios.vars";

// Split Pane
// --------------------------------------------------

.split-pane-ios {
  --border: #{$split-pane-ios-border};
}

.split-pane-ios.split-pane-visible > .split-pane-side {
  min-width: $split-pane-ios-side-min-width;
  max-width: $split-pane-ios-side-max-width;

  border-right: var(--border);
  border-left: 0;
}

.split-pane-ios.split-pane-visible > .split-pane-side[side=end] {
  min-width: $split-pane-ios-side-min-width;
  max-width: $split-pane-ios-side-max-width;

  border-right: 0;
  border-left: var(--border);
}

```

I think more optimized is:
``` scss
@import "./split-pane";
@import "./split-pane.ios.vars";

// Split Pane
// --------------------------------------------------

.split-pane-ios {
  --border: #{$split-pane-ios-border};

  &.split-pane-visible {

    & > .split-pane-side {
      min-width: $split-pane-ios-side-min-width;
      max-width: $split-pane-ios-side-max-width;
      
      border-right: var(--border);
      border-left: 0;

      &[side=end] {
        border-right: 0;
        border-left: var(--border);
      }
    }

  }
}
```

Which structure of scss should I use for the PR and futured PRs your or optimized one provided above?

Thanks!

**Comment by troyanskiy** [comment]
In fact, `max-width` can be overwritten by: 
`app.component.scss`
```scss
:host {
  .split-pane-side {
    max-width: 20%;
  }
}
```
