### ISSUE TITLE
Nested ion-item does not respect nearest ion-list lines property value

### ISSUE THREAD

**Issue by adamduren** [ionic-team/ionic#17135]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When a `ion-list` is nested in a `ion-list` and they have conflicting `lines` property values the outer one is overriding the inner one due to a lack of css specificity.

**Expected behavior:**

That the nearest inner `ion-list` `lines` property take effect the `ion-item`.

**Steps to reproduce:**
See code and screenshot below

**Related code:**

```html
<ion-content>
  <ion-list lines="full">
    <ion-item>
      <ion-label position="stacked">
        Inner List 1
      </ion-label>
      <ion-list style="width: 100%" lines="none">
        <ion-item>
          <ion-label>Inner List 1, Item 1</ion-label>
        </ion-item>
        <ion-item>
          <ion-label>Inner List 1, Item 2</ion-label>
        </ion-item>
        <ion-item>
          <ion-label>Inner List 1, Item 3</ion-label>
        </ion-item>
      </ion-list>
    </ion-item>
    <ion-item>
      <ion-label position="stacked">
        Inner List 2
      </ion-label>
      <ion-list style="width: 100%" lines="none">
        <ion-item>
          <ion-label>Inner List 2, Item 1</ion-label>
        </ion-item>
        <ion-item>
          <ion-label>Inner List 2, Item 2</ion-label>
        </ion-item>
        <ion-item>
          <ion-label>Inner List 2, Item 3</ion-label>
        </ion-item>
      </ion-list>
    </ion-item>
  </ion-list>
</ion-content>
```

**Other information:**

In playing around with the elements debugger the fix seems to simply change places where the style is defined as ancestor to immediate child on the `ion-item`. However I am not sure if this has unintended consequences so currently no pull request. Would be happy to submit one though.

**Before:** 
```css
.list-ios-lines-full .item {
    --inner-border-width: 0;
}

.list-ios-lines-full .item, .list-ios .item-lines-full {
    --border-width: 0 0 0.55px 0;
}

.list-ios-lines-none .item {
    --border-width: 0;
    --inner-border-width: 0;
}
```

![127 0 0 1_4200_provider_manage-base-rate iphone x](https://user-images.githubusercontent.com/581097/51256352-14e7d700-195a-11e9-82a1-64469ee5788c.png)

**After:** 
```css
.list-ios-lines-full > .item {
    --inner-border-width: 0;
}

.list-ios-lines-full > .item,
.list-ios > .item-lines-full {
    --border-width: 0 0 0.55px 0;
}

.list-ios-lines-none > .item {
    --border-width: 0;
    --inner-border-width: 0;
}
```
![127 0 0 1_4200_provider_manage-base-rate iphone x 1](https://user-images.githubusercontent.com/581097/51256382-2b8e2e00-195a-11e9-84be-58a3b09e3d56.png)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/Users/adamduren/.nvm/versions/node/v10.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.0
   @angular-devkit/schematics    : 7.2.0
   @angular/cli                  : 7.2.0
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/adamduren/Library/Android/sdk)
   NodeJS            : v10.14.1 (/Users/adamduren/.nvm/versions/node/v10.14.1/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by adamduren** [comment]
Also can submit a running application if a link to an Ionic-v4 plunker / stackblitz can be provided. The link to plunker in the issue template still references Ionic-v3.

**Comment by brandyscarney** [comment]
Thanks for the issue! I think the problem here is with the structure. What's the use case for a nested list with a wrapping item? The problem with only targeting the immediate child item from a list is this won't work with wrappers, so for example the following use cases would break:

```
<ion-list lines="full">
  <ion-menu-toggle>
    <ion-item>
      <ion-label>Menu Toggle</ion-label>
    </ion-item>
  </ion-menu-toggle>

  <ion-item-sliding>
    <ion-item>
      <ion-label>Item Sliding</ion-label>
    </ion-item>
  </ion-item-sliding>
</ion-list>
```

I created a Codepen to mess around with this, leaving your first list somewhat the same and just adding some styles to override the border manually to see the desired UI. I then removed the nested item/list from the second list and added some styles to item padding left to achieve a similar UI: https://codepen.io/brandyscarney/pen/QzPpZj

Could you let me know if I'm misunderstanding you and this is not what you are looking for? 🙂 

Adding the code below, as well:

<details>

```html
<ion-list lines="none" class="second-list">
  <ion-list-header>
    <ion-label>
      No Inner List
    </ion-label>
  </ion-list-header>
  <ion-item>
    <ion-label>No Inner List 2, Item 1</ion-label>
  </ion-item>
  <ion-item>
    <ion-label>No Inner List 2, Item 2</ion-label>
  </ion-item>
  <ion-item lines="full">
    <ion-label>No Inner List 2, Item 3</ion-label>
  </ion-item>
</ion-list>
```

```css
.second-list ion-item {
  --padding-start: 32px;
}
```

</details>
