### ISSUE TITLE
ion-button ignores --background variables if a color is set

### ISSUE THREAD

**Issue by fifafu** [ionic-team/ionic#17315]
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**
In a corporate theme I'm required to add a gradient to all buttons. The gradient is derived from the color property that is set to a component.

In the betas and as far as I know also in the RCs of Ionic I could override the background like this:

```css
ion-button[class*="ion-color-primary"]:not(.button-outline):not(.button-clear) {
  --background: linear-gradient(
    to bottom,
    #000 0%,
    #fff 100%
  );
}
```
Unfortunately this approach has now also stopped working. 
It would be great if I could just do something like this:

```css
ion-button {
   &.ion-color-primary {
      --background: #somecolor
   }
}
```

**Expected behavior:**
I think the --background property should always be respected, regardless of the button type.
Currently it seems like the --background variable is only used for some of the button types. For solid color buttons the background is just set without using the variable: https://github.com/ionic-team/ionic/blob/74ce34fa68b926777a4166c5eb815866433ae91e/core/src/components/button/button.scss#L86 

I think it should rather be 

```
background: var(--background, current-color(base));
```

**Steps to reproduce:**
Try to override the background variable for a button like this:
```html
<ion-button color="primary">test</ion-button>
```

**Related code:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0
   @angular-devkit/core       : 7.2.3
   @angular-devkit/schematics : 7.2.3
   @angular/cli               : 7.1.4
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

System:

   NodeJS : v11.8.0 (/usr/local/Cellar/node/11.8.0/bin/node)
   npm    : 6.5.0
   OS     : macOS
```

**Comment by brandyscarney** [comment]
Thanks for the issue. This is by design and was decided in the early betas (see #14853). The `color` property will always take precedence over the individual CSS properties. This is because you could do the following:

```
ion-button {
  --background: red;
}
```

and while you'd want all buttons to be background red, you wouldn't want a button that has `<ion-button color="primary">` to have a red background. The thinking is that if you don't want to use the background that comes with the `color` property, you shouldn't add the property at all, and you should use your own CSS or add a new color instead.

It's hard for me to know what exactly you're trying to accomplish without pictures, but below are two ways you can achieve the background color based on our Ionic colors.

You should have the Ionic colors defined in your project for use. If you're using Angular it would be here: https://github.com/ionic-team/ionic-conference-app/blob/master/src/theme/variables.scss

## Add a New Color

Codepen: https://codepen.io/brandyscarney/pen/wNobdY

Here is the CSS from the Codepen:  

```
.ion-color-primary-gradient {
  --ion-color-base: linear-gradient(
      to bottom,
      var(--ion-color-primary) 0%,
      var(--ion-color-primary-contrast) 100%
    );
  --ion-color-base-rgb: 56, 128, 255;
  --ion-color-contrast: #ffffff;
  --ion-color-contrast-rgb: 255, 255, 255;
  --ion-color-shade: #3171e0;
  --ion-color-tint: #4c8dff;
}
```

<img width="394" alt="screen shot 2019-01-30 at 3 12 44 pm" src="https://user-images.githubusercontent.com/6577830/52009691-8a4ac000-24a1-11e9-8fe1-d85173ee6544.png">

## Define Color Classes

Codepen: https://codepen.io/brandyscarney/pen/OdbKyR?editors=1100

This is easier to do with Sass loops, but if you're just using CSS it would be like the following:

```html
<ion-button class="my-primary">
  Primary
</ion-button>
```

```css
.my-primary {
  --background: linear-gradient(
    to bottom,
    var(--ion-color-primary) 0%,
    var(--ion-color-primary-contrast) 100%
  );
}
```
