### ISSUE TITLE
Make Ion-Item --border-width available for all 4 directions

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic#17767]
# Feature Request
Make ion-item css variable `--border-width` available for all directions:
```
--border-width-top
--border-width-right
--border-width-bottom
--border-width-left
```

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Border width for all four directions for easier custom styles

**Describe Preferred Solution**
```
--border-width-top
--border-width-right
--border-width-bottom
--border-width-left
```

**Comment by masimplo** [comment]
I just opened a PR for this, but the fact that --border-width would no longer be supported and thus introduce a breaking change with this PR haunted me. So I tried setting a list of widths as border-width and it seems to work as demonstrated here: https://stackblitz.com/edit/typescript-6twsu6?file=style.css

@Spinnenzunge did you try setting the border-width like:

```css
--border-width: 10px 0px 20px 5px;
```

**Comment by Spinnenzunge** [comment]
That works, but the four different variables makes it way easier to overwrite in subclasses etc. I could generate my own --border-width-direction variables and assign to --border-width but that would kinda be what i requested in the feature request

**Comment by masimplo** [comment]
I see. However breaking the current API and having to declare for variables instead of one when wanting to set a border seems like something a lot of people would dislike. Do you have an example where setting the current variable with four parameters would not work? Is it when you have 2 sides defined and you want to define one more, without redefining previous ones?

I am trying to find a way to support both border-width and border-side-width at the same time, but my CSS variable knowledge is not that extensive. [stackoverflow question](https://stackoverflow.com/questions/55615332/css-custom-properties-variables-for-box-model)
In case you think there is no other way to achieve what you need and @brandyscarney says it is ok to break the API I will be happy to reopen the pull request.

**Comment by brandyscarney** [comment]
Thanks for looking into this @masimplo! We can't introduce any breaking changes to the API without a major version release, and since we just released `v4` we're not looking to release a major version anytime soon (at the earliest should there be 6 months between any major version releases).

For the original issue - would a possible solution be to create your own variables for this? Take the following example:

```
ion-item {
  --border-top-width: 2px;
  --border-end-width: 3px;
  --border-bottom-width: 2px;
  --border-start-width: 6px;
  
  --inner-border-width: 0;
  
  --border-width: var(--border-top-width) var(--border-end-width) var(--border-bottom-width) var(--border-start-width);
  --border-color: red;
}

ion-item:first-child {
  --border-top-width: 0;
}
```

This would allow you to define the variables for all items, then redefine it for specific items/classes. Here's the Codepen for that example: https://codepen.io/brandyscarney/pen/QPpmJP

If this works for you I think it would be the best solution as it avoids adding additional variables to Ionic but still allows you full control and reusability. Please let me know! 🙂

**Comment by masimplo** [comment]
@brandyscarney thanks for taking an interest in this. This is the breaking change I am talking about (maybe it is not considered a breaking change after all?) and it is exactly what I implemented in PR #17990 . People that have defined a --border-width will have to refactor their CSS to define all four new variables to have the same effect. If this is ok, I will be happy to reopen the PR so that it can be reviewed and merged.

I was trying to find a way to support both --border-width and sides at the same time. Something like this: https://stackblitz.com/edit/typescript-boxmodel-css-variables?file=style.css

```css
:root {
  --border-width-top: 0;
  --border-width-right: 0;
  --border-width-bottom: 0;
  --border-width-left: 0;
  --border-width: initial;
}

div {
  border-color: red;
  border-style: solid;
  border-width: var(--border-width, var(--border-width-top) var(--border-width-right) var(--border-width-bottom) var(--border-width-left));
}

div {
  --border-width-top: 10px;
  --border-width-bottom: 10px;

  /* --border-width: 20px; */

/* In case you want to override a previously set --border-width you can just set its value to initial again*/

}
```
The only downside to this is that --border-width takes precedence over sides and it needs to be documented, but this would enable the support of both approaches. You can define a single value (thus not breaking existing codebases) or you can define individual cases. 
@Spinnenzunge would this approach help your situation at all, or does it still create an issue on your particular case?
