### ISSUE TITLE
Ionic 4 Modal dynamic height

### ISSUE THREAD

**Issue by D4rkMindz** [ionic-team/ionic#17999]
Sorry to bother, but there is absolutely no answer on the internet. Everything is about Ionic 3, but i'm currently developing with Ionic 4.

I'm trying to create a modal with a dynamic height. Some resources recommend to use `height: auto`, others rely on scss variables from ionic 3.
Also the forum does not support Ionic 4 questions (this makes it even harder to find a solution).

The goal is the same as here:
https://forum.ionicframework.com/t/dynamic-modal-height-based-on-content/100732

The full codebase can be found here:
https://github.com/wavetrophy/app/tree/5871ae5dd3ccffb531c8ee3344329f79aa28dc1f

My Code:
[`src/global.scss`](https://github.com/wavetrophy/app/blob/5871ae5dd3ccffb531c8ee3344329f79aa28dc1f/src/global.scss)
```css
.modal-auto-height {

  .modal-wrapper {
    display: flex;
    min-height: 20vh;
    height: auto;
  }
  .ion-page {
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;

  }
}
```

[`src/app/modal/edit/email.page.html`](https://github.com/wavetrophy/app/blob/5871ae5dd3ccffb531c8ee3344329f79aa28dc1f/src/app/modal/edit/email.page.html)
```html
<ion-content padding class="modal-content">
    <h3>{{title}}</h3>
    <ion-item>
        <ion-input type="text" value="{{value}}" #input></ion-input>
    </ion-item>
    <ion-row justify-content-between margin-top="1vh">
        <span></span>
        <div>
            <ion-button fill="clear" (click)="close()">Cancel</ion-button>
            <ion-button fill="clear" (click)="save()">Save</ion-button>
        </div>
    </ion-row>
</ion-content>
```

The actual result:
![image](https://user-images.githubusercontent.com/16854141/55781281-1aad0e80-5aaa-11e9-9995-9f1051d63c12.png)

I really appreciate any help.
