### ISSUE TITLE
bug: Ionic 4 card color only affects the text color.

### ISSUE THREAD

**Issue by Domvel** [ionic-team/ionic#19197]
# Bug Report

**Ionic version:**
`4.7.1`

**Current behavior:**
The color property of `ion-card` only affects the text color.

```html
<ion-card color="danger">
  <ion-card-header>
    Hello World
  </ion-card-header>
</ion-card>
```

Results to:
![image](https://user-images.githubusercontent.com/35452565/63780281-24fc6780-c8e8-11e9-95e0-1073e05b3b3f.png)

**Expected behavior:**
The color attribut of `ion-card` should also affect to the background-color.
And the text color in contrast. (like already works.)

![image](https://user-images.githubusercontent.com/35452565/63780823-021e8300-c8e9-11e9-8a1d-37d9d43a2e06.png)

**Steps to reproduce:** / **Related code:**
There is no official Ionic 4 template in Stackblitz. 
But I think this does not need a demo.
Because the code snippets here and screenshots completely describes the issue.
Please let me know, if you still want some demos.
See the **Current behavior** section above for an example.

**Comment by domske** [comment]
The current master and the tag 4.7.1 works. See [source code](https://github.com/ionic-team/ionic/blob/v4.7.1/core/src/components/card/test/basic/index.html#L63) test.
I'll test it in a new Ionic 4 project...

**Comment by paulstelzer** [comment]
Thanks for your issue! There is an official Ionic4 template on Stackblitz. You can find it here -> https://stackblitz.com/edit/ionic-v4-angular-tabs

I tried your code and it works like your described -> https://stackblitz.com/edit/ionic-v4-angular-tabs-8sw5fv?file=src/app/tab1/tab1.page.html

**Comment by Domvel** [comment]
Thanks and sorry. It was a variable in variable.scss. 

```css
// Default
--ion-item-background: #ffffff;
// Dark
--ion-item-background: #1a1b1e;
```
But I want this variable. I tought it's the default value. 
I expected that the color attribute on an item / element is dominant.
Is this a bug? Or is there another way to set the default color. 
I thinks it's a bug. Because I don't want to overwrite the color-attribute (danger, etc.).
You can close this issue if this works like expected. But I wondering how to set the default background of items in themes?

Please look at this:
https://stackblitz.com/edit/ionic-v4-angular-tabs-3d4cz6?embed=1&file=src/app/tab1/tab1.page.html
Bug or not?

**Comment by Domvel** [comment]
A workaround is: 

```css
.my-card {
  --background: var(--ion-color-danger);
}
```
[See demo](https://stackblitz.com/edit/ionic-v4-angular-tabs-2tgqsz?embed=1&file=src/app/tab1/tab1.page.scss)

But I want the official way `color` attribute. :baby: I think it's a bug.

**Comment by domske** [comment]
The problem is not the `ion-card` itself, it's the `ion-card-header`. As you can see in the [demo](https://stackblitz.com/edit/ionic-v4-angular-tabs-3d4cz6?embed=1&file=src/styles.css) posted before.
Because the header also has a background color and uses the `ion-item-background`.

Solution:

**card.scss**
```scss
:host(.ion-color) {
  background: current-color(base);
  color: current-color(contrast);
}

:host(.ion-color)::slotted(*) ion-card-header,
:host(.ion-color)::slotted(*) ion-card-title,
:host(.ion-color)::slotted(*) ion-card-subtitle {
  background: current-color(base);
  color: current-color(contrast);
}
```
