### ISSUE TITLE
feat: Support animation style prop from IonContent

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/ionic#19957]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Please support animation for IonContent element.

**Describe Preferred Solution**
Include new prop to support animation style.

**Describe Alternatives**
Adding the value via TS, but it's not working. e.g:
```ts
const contentElement = (this.content['el'] as HTMLElement);
const innerScroll = contentElement.shadowRoot.querySelector('.inner-scroll') as HTMLElement;
innerScroll.style.animation = 'background 30s ease infinite';
```

**Related Code**
```scss
ion-content {
  --background: linear-gradient(124deg, #ff2400, #e81d1d, #e8b71d, #e3e81d, #1de840, #1ddde8, #2b1de8, #dd00f3, #dd00f3);
  --animation: background 30s ease infinite;
}

@keyframes background {
    0%{background-position:0% 50%}
    50%{background-position:100% 50%}
    100%{background-position:0% 50%}
}
```

Thanks in advance!
