### ISSUE TITLE
bug: Scroll bar in Dark mode Freaks out appbar

### ISSUE THREAD

**Issue by vixalien** [ionic-team/ionic#21064]
# Scroll bar in Dark mode Freaks out appbar

> Pre notice: I can't figure out whether this is a bug or a docs issue, but as it affect all ionic apps, let's make it a bug.

**Ionic version:** 
[x] **Latest**, or whatever you use at [Ionic Docs Page](https://ionicframework.com/docs)

**Current behavior:**
When in dark mode, the scroll bar in chrome is still white, and when the blur effect in the navbar or appbar is applied, there is a large white shadow-like object in the background of the appbar

![ionic issue](https://user-images.githubusercontent.com/37999241/79533107-67d99e00-8077-11ea-90a3-2579503f33c0.png)

**Expected behavior:**
The app-bar should have a completely dark background

**Steps to reproduce:**
In chrome 80 on windows, navigate to [The Ionic framework docs page](https://ionicframework.com/docs) and in the all components example, look at the appbar.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The scrollbar styling is controlled by the OS, so it only changes when dark mode is set at an OS level.

You can indicate to the browser that you would like to use the dark mode scrollbar via `color-scheme`: https://ionicframework.com/docs/theming/dark-mode#adjusting-system-ui-components.

**Comment by vixalien** [comment]
Fix 1:
====
I think the correct handling of this issue is to provide consistent layout for the `<ion-app>`.

Now, I think the header has `position: fixed` whereas the layout system would be that `<ion-header>` and `<ion-body>` are two separate components, where none will interfere with another's scroll target

Fix 2: 
====
Making the scroll-bar dark, but this is not supported in all browsers, chrome at least support that:
```css
html {
  scrollbar-face-color: #646464;
  scrollbar-base-color: #646464;
  scrollbar-3dlight-color: #646464;
  scrollbar-highlight-color: #646464;
  scrollbar-track-color: #000;
  scrollbar-arrow-color: #000;
  scrollbar-shadow-color: #646464;
  scrollbar-dark-shadow-color: #646464;
}

::-webkit-scrollbar { width: 8px; height: 3px;}
::-webkit-scrollbar-button {  background-color: #666; }
::-webkit-scrollbar-track {  background-color: #646464;}
::-webkit-scrollbar-track-piece { background-color: #000;}
::-webkit-scrollbar-thumb { height: 50px; background-color: #666; border-radius: 3px;}
::-webkit-scrollbar-corner { background-color: #646464;}}
::-webkit-resizer { background-color: #666;}
```
Codepen demo: https://codepen.io/subfauna/pen/CLtmF
