### ISSUE TITLE
bug: Modal backdrop opacity css variable doesn't work

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic#21551]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

For example I set the backdrop opacity to 1 in the `global.scss` file. But it doesn't change anything. Here is an example: https://github.com/mariusbolik/ionic-modal

```css
ion-modal {
  --backdrop-opacity: 1 !important;
}
```

**Expected behavior:**

Modal backdrop should become darker.

---

Thank you for you great work & best regards
Marius
