### ISSUE TITLE
background image on ion-content: image resize when keyboard open

### ISSUE THREAD

**Issue by royipressburger** [ionic-team/ionic#7631]
#### Short description of the problem:

If you set backgound image on `ion-content`:

``` css
.backgound-image {
  background-image: url('../image.jpg');
  width: 100%;
  background-size: 100% 100%;
  background-repeat: no-repeat;
  background-position: center center;
}
```

When the keyboard open the image is resized to the new view port instead of staying the same size
#### What behavior are you expecting?

Was expecting that image will stay at same size as it was when the keyboard was closed

**Steps to reproduce:**
1. create a page with some input
2. add backgound image on `ion-content`
3. deploy on android and focus the input 

I did not tested that on ios.. just android.. but i guess its the same behaviour
**Which Ionic Version?** 1.x or 2.x
2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/aRWWybwruymTbJuu69M2?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID: Ubuntu Description: Ubuntu 14.04.4 LTS 
Node Version: v5.9.0
